# Generated by Django 3.0.14 on 2022-07-07 17:21

from django.db import migrations, models
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('aId', models.CharField(max_length=80)),
                ('Name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Account',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('oId', models.CharField(max_length=80)),
                ('Name', models.CharField(max_length=80)),
                ('Amount', models.CharField(max_length=80)),
                ('AccountId', models.CharField(max_length=80)),
                ('OwnerId', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Opportunity',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('uId', models.CharField(max_length=80)),
                ('Name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'User',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
