# Generated by Django 3.0.14 on 2022-07-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220707_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='AccountId',
            field=models.ForeignKey(db_column='AccountId', on_delete=django.db.models.deletion.CASCADE, to='base.Account'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='Amount',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='OwnerId',
            field=models.ForeignKey(db_column='OwnerId', on_delete=django.db.models.deletion.CASCADE, to='base.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
